Only check version bump when not on main

diff --git a/.github/workflows/bump.yml b/.github/workflows/bump.yml
--- a/.github/workflows/bump.yml
+++ b/.github/workflows/bump.yml
@@ -6,4 +6,10 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - run: |
-          [[ $(git show main:pyproject.toml | grep version) == $(cat pyproject.toml | grep version) ]]
+          if [[ 
+            $(git rev-parse --abbrev-ref HEAD) != main &&
+            $(git show main:pyproject.toml | grep version) != $(cat pyproject.toml | grep version)
+          ]]; then
+            echo "Version bump required"
+            exit 1
+          fi
